### ISSUE TITLE
[FEATURE] Markdown compatability for the Description Field

### ISSUE THREAD

**Issue by Theysen** [KSP-RO/RP1AnalyticsWebApp#7]
Implement basic markdown functionality for the "description" field

**Comment by Theysen** [comment]
will be done via https://github.com/KSP-RO/RP1AnalyticsWebApp/pull/10

**Comment by lpgagnon** [comment]
this seems to only be half-working. In particular, bullet and numbered lists don't actually get rendered as such

**Comment by Theysen** [comment]
It's never been in?

**Comment by Theysen** [comment]
nevermind, seems siimav merged it, despite only negative feedback on that feature because images / etc weren't wanted in the description.
